FROM python:3.7

RUN pip install mlflow==1.14.1

# RUN echo foo
# Install mlflow containing a patch for the issue
# RUN pip install git+https://github.com/dolfinus/mlflow.git@fix_1.15_migration

RUN pip install psycopg2

COPY mlflow_log.py /mlflow_log.py

