version: "3"
services:
  postgres:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: mlflowuser
      POSTGRES_PASSWORD: mlflowpassword
      POSTGRES_DB: mlflowdb
  server:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      MLFLOW_TRACKING_URI: postgresql://mlflowuser:mlflowpassword@postgres:5432/mlflowdb
    command: bash -c "python /mlflow_log.py"
