FROM python:3.7

WORKDIR /app

RUN pip install mlflow==1.15.0

# RUN pip install -U git+https://github.com/dolfinus/mlflow.git@fix_1.15_migration

RUN pip install pymysql mysqlclient pandas

COPY mlflow_log_mysql.py mlflow_log_mysql.py
