version: "3"
services:
  postgres:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow

  server:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MLFLOW_TRACKING_URI: postgresql://mlflow:mlflow@postgres:5432/mlflow
      # MLFLOW_TRACKING_URI: sqlite:////mlflow.db
    command: bash -c "python /mlflow_log.py"
